# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pheonix', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'member', 'verbose_name_plural': 'members'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-sent_at'], 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='send_at',
            new_name='sent_at',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='send_by',
            new_name='sent_by',
        ),
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
    ]
